[package]
name = "prose"
version = "0.1.0"
authors = ["hg.king <hgmaxwellking@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "6.1.2"

regex = "1"

[dependencies.nom]
version = "6.0.0-alpha"
